src/Entity/Job.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\JobRepository;

/**
 * @ORM\Entity(repositoryClass=JobRepository::class)
 */
class Job
{

    const CONTRACT = ['CDI', 'CDD', 'Stage'];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $experience;

    /**
     * @ORM\Column(type="integer")
     */
    private $salary;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $is_available;

    /**
     * @ORM\Column(type="text")
     */
    private $company;

    /**
     * @ORM\Column(type="integer")
     */
    private $contract;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_remote_only;

    /**
     * @ORM\ManyToMany(targetEntity=Techno::class, inversedBy="jobs")
     */
    private $technos;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->technos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getExperience(): ?int
    {
        return $this->experience;
    }

    public function setExperience(?int $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function getFormatedSalary(): string
    {
        return number_format($this->salary, 0, '', ' ');
    }

    public function setSalary(int $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available = true): self
    {
        $this->is_available = $is_available;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getContract(): ?int
    {
        return $this->contract;
    }

    public function setContract(int $contract): self
    {
        $this->contract = $contract;

        return $this;
    }

    public function getIsRemoteOnly(): ?bool
    {
        return $this->is_remote_only;
    }

    public function setIsRemoteOnly(bool $is_remote_only): self
    {
        $this->is_remote_only = $is_remote_only;

        return $this;
    }

    /**
     * @return Collection|Techno[]
     */
    public function getTechnos(): Collection
    {
        return $this->technos;
    }

    public function addTechno(Techno $techno): self
    {
        if (!$this->technos->contains($techno)) {
            $this->technos[] = $techno;
            $techno->addJob($this);
        }

        return $this;
    }

    public function removeTechno(Techno $techno): self
    {
        if ($this->technos->removeElement($techno)) {
            $techno->removeJob($this);
        }

        return $this;
    }
}

src/Form/JobType.php
<?php

namespace App\Form;

use App\Entity\Job;
use App\Entity\Techno;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('company')
            ->add('contract', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('description')
            ->add('experience')
            ->add('salary')
            ->add('technos',
                EntityType::class,
                [
                    'class' => Techno::class,
                    'multiple' => true,
                    'choice_label' => 'name',
                    'attr' => ['class'=>'select-techno']
                ]
            )
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('is_remote_only')
            ->add('is_available');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Job::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        return array_flip(Job::CONTRACT);
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Entity\JobSearch;
use App\Form\JobSearchType;
use App\Repository\JobRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class JobController extends AbstractController
{

    /**
     * @var JobRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;


    public function __construct(
        JobRepository $repository,
        EntityManagerInterface $em
    )
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/jobs", name="job.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new JobSearch();
        $form = $this->createForm(JobSearchType::class, $search);
        $form->handleRequest($request);

        $jobs = $paginator->paginate(
            $this->repository->findAllAvailableQuery($search),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render(
            'job/index.html.twig',
            [
                'current_menu' => 'job',
                'jobs' => $jobs,
                'form' => $form->createView()
            ]
        );
    }

    /**
     * @Route("/jobs/{slug}-{id}", name="job.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Job $job
     * @param string $slug
     * @return Response
     */
    public function show(Job $job, string $slug): Response
    {
        if ($job->getSlug() !== $slug) {
            return $this->redirectToRoute('job.show',
                [
                    'id' => $job->getId(),
                    'slug' => $job->getSlug()
                ],
                301
            );
        }
        return $this->render(
            'job/show.html.twig',
            ['job' => $job, 'current_menu' => 'job']
        );
    }


}

templates/job/_job.html.twig
<div class="card mb-4">
    <div class="card-body">
        <h5>
            <a href="{{ path('job.show', {slug: job.slug, id: job.id}) }}">
                {{ job.title }}
            </a>
        </h5>
        <p class="card-text">
            {{ job.city }} ({{ job.postalCode }})
        </p>
        <div class="text-primary">
            {{ job.formatedSalary }} €
        </div>
    </div>
</div>

templates/job/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'All Jobs' %}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.address) }}
                </div>
                <div class="col">
                    {{ form_row(form.minSalary) }}
                </div>
                <div class="col">
                    {{ form_row(form.technos) }}
                </div>
                <div class="col">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4 text-center">
        <h1> All Jobs </h1>
        <div class="row">
            {% for job in jobs %}
                <div class="col-md-4">
                    {% include 'job/_job.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(jobs) }}
        </div>
    </div>
{% endblock %}

templates/job/show.html.twig
{% extends 'base.html.twig' %}
{% block title  job.title %}
{% block body %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">

            </div>
            <div class="col-md-4">
                <h1> {{ job.title }}</h1>
                <h2> {{ job.experience }} annee(s)</h2>
                <div class="text-primary" style="font-size: 4rem;font-weight: bold;"> {{ job.formatedSalary }}</div>
                <a href="#" class="btn btn-primary"> Postuler</a>
            </div>
        </div>
        <p> {{ job.description | nl2br }}</p>
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
{% endblock %}